Database database = session.getDatabase("playground");
Store store = database.getStore("pinball");
String s = "";

// The document is generated by the Darwino runtime when a document
// is created, and is unique across the whole database
// As it is not predictable, we first load the document by UNID and grab its id
Document doc = store.loadDocument("1000");
int id = doc.getDocId();

Document doc2 = database.loadDocumentById(id);

s += ">> Document\n";
s += "  Unid: "+doc.getUnid()+"\n";
s += "  Id: "+doc.getDocId()+"\n";
s += "  Json: "+doc.getJsonString(false)+"\n";

_formatText("{0}",s);