session.setAsync(false);

var database = session.getDatabase("playground");
var store = database.getStore("pinball");
var s = "";

// The document is generated by the Darwino runtime when a document
// is created, and is unique across the whole database
// As it is not predictable, we first load the document by UNID and grab its id
var doc = store.loadDocument("1000");
var id = doc.getDocId();

var doc2 = database.loadDocumentById(id);

s += ">> Document\n"
s += "  Unid: "+doc.getUnid()+"\n"
s += "  Id: "+doc.getDocId()+"\n"
s += "  Json: "+doc.getJsonString()+"\n"

darwino.Utils.setText("content","{0}",s);